swagger: "2.0"
info:
  version: "0.0.1"
  title: Swan Micro Services
host: localhost:3002
basePath: /
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /users/register:
    x-swagger-router-controller: userController
    post:
      description: Create a user with Client role
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessCreation"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  SuccessCreation:
     type: object
     properties:
      message:
        type: string
        example: Succesfully stored to database.
  CreateUserRequest:
    required:
      - name
      - email
      - password
      - gender
      - phonenumber
      - role
    type: object
    properties:
      name:
        type: string
        example: kranthi
      email:
        type: string
        example: xyz@abc.com
      password:
        type: string
        example: kranthi
      gender:
        type: string
        example: M
        enum:
          - M
          - F
      phonenumber:
        type: number
        example: 1234
      role:
        type: string
        example: client
        enum:
          - client
          - admin
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string